hyscale/hyscale

- README.md
- add: logo
- emphasize: parts
- remove: `$` from command snippets, preventing people from accidentally copy-pasting it.
> chore(readme): logo, formatting

- commons/src/main/java/io/hyscale/commons/commands/CommandExecutor.java
- commons/src/main/java/io/hyscale/commons/constants/ToolConstants.java
- commons/src/main/java/io/hyscale/commons/models/ConfigTemplate.java
- commons/src/main/java/io/hyscale/commons/utils/HyscaleFilesUtil.java
- commons/src/main/java/io/hyscale/commons/utils/ObjectMapperFactory.java
- commons/src/main/java/io/hyscale/commons/utils/OperatingSystemHelper.java
- dockerfile-generator/dockerfile-gen-services/src/main/java/io/hyscale/dockerfile/gen/services/templates/CommandsTemplateProvider.java
- dockerfile-generator/dockerfile-gen-services/src/main/java/io/hyscale/dockerfile/gen/services/templates/DockerfileTemplateProvider.java
- image-builder/builder-services/src/main/java/io/hyscale/builder/services/constants/DockerImageConstants.java
- manifest-generator/generator-services/src/main/java/io/hyscale/generator/services/utils/PluginHandlers.java
- service-spec/service-spec-commons/src/main/java/io/hyscale/servicespec/commons/model/service/Artifact.java
- service-spec/service-spec-commons/src/main/java/io/hyscale/servicespec/commons/model/service/BuildSpec.java
- service-spec/service-spec-commons/src/main/java/io/hyscale/servicespec/commons/model/service/Dockerfile.java
- service-spec/service-spec-commons/src/main/java/io/hyscale/servicespec/commons/model/service/Props.java
- service-spec/service-spec-commons/src/main/java/module-info.java
- service-spec/service-spec-commons/src/test/java/io/hyscale/servicespec/BaseFieldsTest.java
- workflow-controller/controller-service/src/main/java/io/hyscale/controller/commands/HyscaleDeployServiceCommand.java
- workflow-controller/controller-service/src/main/java/io/hyscale/controller/commands/HyscaleGenerateServiceManifestsCommand.java
- workflow-controller/controller-service/src/main/java/io/hyscale/controller/directive/ServiceSpecDirectiveUpdateHandler.java
- workflow-controller/controller-service/src/main/java/io/hyscale/controller/directive/impl/BuildSpecJsonHandler.java
- workflow-controller/controller-service/src/main/java/io/hyscale/controller/directive/impl/DockerfileJsonHandler.java
- workflow-controller/controller-service/src/main/java/io/hyscale/controller/directive/impl/PropsJsonHandler.java
- workflow-controller/controller-service/src/main/java/io/hyscale/controller/initializer/HyscaleInitializer.java
- workflow-controller/controller-service/src/main/java/io/hyscale/controller/util/EffectiveServiceSpecUtil.java
- workflow-controller/controller-service/src/main/java/io/hyscale/controller/util/ResourceCleanUpUtil.java
- workflow-controller/controller-service/src/main/java/io/hyscale/controller/util/ServiceSpecMapper.java
Updating service spec with unix file separator
Command Executor, read buffer to avoid deadlock
> Windows Support

- commons/src/main/java/io/hyscale/commons/commands/CommandExecutor.java
- commons/src/main/java/io/hyscale/commons/models/CredsStoreEntity.java
- commons/src/main/java/io/hyscale/commons/models/DockerCredHelper.java
> 1.logger statements for credstore

- commons/src/main/java/io/hyscale/commons/commands/CommandExecutor.java
- commons/src/main/java/io/hyscale/commons/exception/CommonErrorCode.java
- commons/src/main/java/io/hyscale/commons/utils/LogProcessor.java
- commons/src/main/java/io/hyscale/commons/utils/MustacheTemplateResolver.java
- commons/src/main/java/io/hyscale/commons/utils/NormalizationUtil.java
- commons/src/main/java/io/hyscale/commons/utils/ResourceLabelBuilder.java
- image-builder/builder-services/src/main/java/io/hyscale/builder/services/config/ImageBuilderConfig.java
- image-builder/builder-services/src/main/java/io/hyscale/builder/services/util/ImageLogUtil.java
- manifest-generator/generator-services/src/main/java/io/hyscale/generator/services/utils/AgentHelper.java
- workflow-controller/controller-service/src/main/java/io/hyscale/controller/util/LoggerUtility.java
1.handling exceptions
2.handling null and invalid inputs
3.adding loggers at required
> Commons Module: Code fixes for input validation

- commons/src/main/java/io/hyscale/commons/utils/LogProcessor.java
- image-builder/builder-services/src/main/java/io/hyscale/builder/services/util/ImageLogUtil.java
1. in case of tail,removed unnecessary throws at places where specified
> Removed exceptions and refractored

- commons/src/main/java/io/hyscale/commons/models/DockerCredHelper.java
- commons/src/main/java/io/hyscale/commons/models/ImageRegistry.java
- image-builder/builder-services/src/main/java/io/hyscale/builder/services/command/ImageCommandGenerator.java
- image-builder/builder-services/src/main/java/io/hyscale/builder/services/util/DockerImageUtil.java
- manifest-generator/generator-services/src/main/java/io/hyscale/generator/services/plugins/ImagePullSecretHandler.java
- workflow-controller/controller-service/src/main/java/io/hyscale/controller/builder/ImageRegistryBuilder.java
Adds support for service account.
> Docker config: using token instead of username and password

- manifest-generator/generator-services/src/main/java/io/hyscale/generator/services/plugins/AutoScalingPluginHandler.java
- service-spec/service-spec-commons/src/main/java/io/hyscale/servicespec/commons/model/service/ReplicasDeserializer.java
- workflow-controller/controller-service/src/main/java/io/hyscale/controller/commands/HyscaleGenerateServiceManifestsCommand.java
> Replicas fix

- commons/src/main/java/io/hyscale/commons/constants/ToolConstants.java
- image-builder/builder-services/src/main/java/io/hyscale/builder/services/impl/LocalImagePushServiceImpl.java
- manifest-generator/generator-services/src/main/java/io/hyscale/generator/services/plugins/ImageHandler.java
- service-spec/service-spec-commons/src/main/java/io/hyscale/servicespec/commons/model/service/ImageDeserializer.java
- service-spec/service-spec-commons/src/main/java/io/hyscale/servicespec/commons/util/ImageUtil.java
Fetching only Sha sum for image using the inspect command
> Image repo digest changes

- workflow-controller/controller-service/src/test/java/io/hyscale/controller/ControllerTestConfiguration.java
Fix: mock config for test cases
> Build failure fix

- commons/src/main/java/io/hyscale/commons/constants/ValidationConstants.java
- deployer/deployer-services/src/main/java/io/hyscale/deployer/services/util/KubernetesVolumeUtil.java
- workflow-controller/controller-service/src/main/java/io/hyscale/controller/commands/HyscaleAppStatusCommand.java
- workflow-controller/controller-service/src/main/java/io/hyscale/controller/commands/HyscaleDeployServiceCommand.java
- workflow-controller/controller-service/src/main/java/io/hyscale/controller/commands/HyscaleGenerateServiceManifestsCommand.java
- workflow-controller/controller-service/src/main/java/io/hyscale/controller/commands/HyscaleServiceLogsCommand.java
- workflow-controller/controller-service/src/main/java/io/hyscale/controller/commands/HyscaleServiceStatusCommand.java
- workflow-controller/controller-service/src/main/java/io/hyscale/controller/commands/HyscaleUndeployAppCommand.java
- workflow-controller/controller-service/src/main/java/io/hyscale/controller/commands/HyscaleUndeploySeviceCommand.java
- workflow-controller/controller-service/src/main/java/io/hyscale/controller/util/CommandUtil.java
> Input validation for app name, service name and namespace

- commons/src/main/java/io/hyscale/commons/exception/HyscaleException.java
- commons/src/main/java/io/hyscale/commons/logger/WorkflowLogger.java
- deployer/deployer-services/src/main/java/io/hyscale/deployer/services/exception/DeployerErrorCodes.java
- deployer/deployer-services/src/main/java/io/hyscale/deployer/services/handler/ResourceLifeCycleHandler.java
- deployer/deployer-services/src/main/java/io/hyscale/deployer/services/handler/impl/NamespaceHandler.java
- deployer/deployer-services/src/main/java/io/hyscale/deployer/services/handler/impl/V1ConfigMapHandler.java
- deployer/deployer-services/src/main/java/io/hyscale/deployer/services/handler/impl/V1DeploymentHandler.java
- deployer/deployer-services/src/main/java/io/hyscale/deployer/services/handler/impl/V1HorizontalPodAutoScalerHandler.java
- deployer/deployer-services/src/main/java/io/hyscale/deployer/services/handler/impl/V1PersistentVolumeClaimHandler.java
- deployer/deployer-services/src/main/java/io/hyscale/deployer/services/handler/impl/V1PodHandler.java
- deployer/deployer-services/src/main/java/io/hyscale/deployer/services/handler/impl/V1SecretHandler.java
- deployer/deployer-services/src/main/java/io/hyscale/deployer/services/handler/impl/V1ServiceHandler.java
- deployer/deployer-services/src/main/java/io/hyscale/deployer/services/handler/impl/V1StatefulSetHandler.java
- deployer/deployer-services/src/main/java/io/hyscale/deployer/services/util/ExceptionHelper.java
- deployer/deployer-services/src/main/java/io/hyscale/deployer/services/util/K8sResourceDispatcher.java
- workflow-controller/controller-service/src/main/java/io/hyscale/controller/commands/HyscaleAppStatusCommand.java
- workflow-controller/controller-service/src/main/java/io/hyscale/controller/commands/HyscaleServiceStatusCommand.java
- workflow-controller/controller-service/src/main/java/io/hyscale/controller/invoker/UndeployComponentInvoker.java
- workflow-controller/controller-service/src/main/java/io/hyscale/controller/util/UndeployCommandUtil.java
> Wait for deletion, exception fix

- commons/src/main/java/io/hyscale/commons/component/ComponentInvoker.java
- commons/src/main/java/io/hyscale/commons/constants/ToolConstants.java
- workflow-controller/controller-service/src/main/java/io/hyscale/controller/activity/ControllerActivity.java
- workflow-controller/controller-service/src/main/java/io/hyscale/controller/commands/HyscaleAppStatusCommand.java
- workflow-controller/controller-service/src/main/java/io/hyscale/controller/commands/HyscaleCommand.java
- workflow-controller/controller-service/src/main/java/io/hyscale/controller/commands/HyscaleDeployCommand.java
- workflow-controller/controller-service/src/main/java/io/hyscale/controller/commands/HyscaleDeployServiceCommand.java
- workflow-controller/controller-service/src/main/java/io/hyscale/controller/commands/HyscaleGenerateCommand.java
- workflow-controller/controller-service/src/main/java/io/hyscale/controller/commands/HyscaleGenerateServiceCommand.java
- workflow-controller/controller-service/src/main/java/io/hyscale/controller/commands/HyscaleGenerateServiceManifestsCommand.java
- workflow-controller/controller-service/src/main/java/io/hyscale/controller/commands/HyscaleGetAppCommand.java
- workflow-controller/controller-service/src/main/java/io/hyscale/controller/commands/HyscaleGetCommand.java
- workflow-controller/controller-service/src/main/java/io/hyscale/controller/commands/HyscaleGetServiceCommand.java
- workflow-controller/controller-service/src/main/java/io/hyscale/controller/commands/HyscaleServiceLogsCommand.java
- workflow-controller/controller-service/src/main/java/io/hyscale/controller/commands/HyscaleServiceStatusCommand.java
- workflow-controller/controller-service/src/main/java/io/hyscale/controller/commands/HyscaleUndeployAppCommand.java
- workflow-controller/controller-service/src/main/java/io/hyscale/controller/commands/HyscaleUndeployCommand.java
- workflow-controller/controller-service/src/main/java/io/hyscale/controller/commands/HyscaleUndeploySeviceCommand.java
- workflow-controller/controller-service/src/main/java/io/hyscale/controller/exception/ExceptionHandler.java
- workflow-controller/controller-service/src/main/java/io/hyscale/controller/exception/ExitCodeExceptionMapper.java
- workflow-controller/controller-service/src/main/java/io/hyscale/controller/initializer/HyscaleInitializer.java
- workflow-controller/controller-service/src/main/java/io/hyscale/controller/invoker/DeployComponentInvoker.java
- workflow-controller/controller-service/src/main/java/io/hyscale/controller/invoker/DockerfileGeneratorComponentInvoker.java
- workflow-controller/controller-service/src/main/java/io/hyscale/controller/invoker/ImageBuildComponentInvoker.java
- workflow-controller/controller-service/src/main/java/io/hyscale/controller/invoker/ManifestGeneratorComponentInvoker.java
- workflow-controller/controller-service/src/main/java/io/hyscale/controller/invoker/UndeployComponentInvoker.java
- workflow-controller/controller-service/src/main/java/io/hyscale/controller/util/LoggerUtility.java
0 - Success
2 - Invalid input
11 - Hyscale exception
> Exit code for commands

- manifest-generator/generator-services/src/main/java/io/hyscale/generator/services/utils/ReplicasUtil.java
Should be greater than 0
Only Integer value with %
> Replicas cpu threshold fix

- CHANGELOG.md
- README.md
> Updated README  & CHANGELOG  

- manifest-generator/generator-services/src/main/java/io/hyscale/generator/services/builder/DefaultLabelBuilder.java
- manifest-generator/generator-services/src/main/java/io/hyscale/generator/services/generator/MetadataManifestSnippetGenerator.java
- manifest-generator/generator-services/src/main/java/io/hyscale/generator/services/model/ManifestResource.java
- manifest-generator/generator-services/src/main/java/io/hyscale/generator/services/model/ServiceMetadata.java
- manifest-generator/generator-services/src/main/java/io/hyscale/generator/services/plugins/AutoScalingPluginHandler.java
- manifest-generator/generator-services/src/main/java/io/hyscale/generator/services/plugins/ConfigMapDataHandler.java
- manifest-generator/generator-services/src/main/java/io/hyscale/generator/services/plugins/ImagePullSecretHandler.java
- manifest-generator/generator-services/src/main/java/io/hyscale/generator/services/plugins/MetaDataHandler.java
- manifest-generator/generator-services/src/main/java/io/hyscale/generator/services/plugins/PodSpecEnvHandler.java
- manifest-generator/generator-services/src/main/java/io/hyscale/generator/services/plugins/PodSpecLabels.java
- manifest-generator/generator-services/src/main/java/io/hyscale/generator/services/plugins/SecretsDataHandler.java
- manifest-generator/generator-services/src/main/java/io/hyscale/generator/services/plugins/SelectorLabelsHandler.java
- manifest-generator/generator-services/src/main/java/io/hyscale/generator/services/plugins/VolumeMountsHandler.java
- manifest-generator/generator-services/src/main/java/io/hyscale/generator/services/plugins/VolumeTemplatesHandler.java
- manifest-generator/generator-services/src/main/java/io/hyscale/generator/services/plugins/VolumesHandler.java
- workflow-controller/controller-service/src/main/java/io/hyscale/controller/commands/HyscaleGetDeploymentsCommand.java
Displaying deployments in alphabatic order
> Renaming manifest AppMetaData to ServiceMetadata.

- deployer/deployer-services/src/main/java/io/hyscale/deployer/services/deployer/impl/KubernetesDeployer.java
- deployer/deployer-services/src/main/java/io/hyscale/deployer/services/exception/DeployerErrorCodes.java
- deployer/deployer-services/src/main/java/io/hyscale/deployer/services/handler/impl/V1ServiceHandler.java
Resolves: https://github.com/hyscale/hyscale/issues/192
> Service address: using labels instead of name

- deployer/deployer-services/src/main/java/io/hyscale/deployer/services/handler/PodParentHandler.java
- deployer/deployer-services/src/main/java/io/hyscale/deployer/services/handler/impl/V1DeploymentHandler.java
- deployer/deployer-services/src/main/java/io/hyscale/deployer/services/handler/impl/V1StatefulSetHandler.java
- deployer/deployer-services/src/main/java/io/hyscale/deployer/services/model/DeployerActivity.java
- docs/hyscale-commands-reference.md
- pom.xml
- workflow-controller/controller-service/src/main/java/io/hyscale/controller/commands/scale/HyscaleScaleServiceCommand.java
- workflow-controller/controller-service/src/main/java/io/hyscale/controller/hooks/K8SResourcesCleanUpHook.java
Feature request: https://github.com/hyscale/hyscale/issues/204
> Upgrading kuberentes client to 8.0.2

- commons/src/main/java/io/hyscale/commons/models/AnnotationKey.java
- deployer/deployer-core/src/main/java/io/hyscale/deployer/core/model/ResourceKind.java
- deployer/deployer-services/src/main/java/io/hyscale/deployer/services/util/K8sResourceDispatcher.java
- manifest-generator/generator-services/src/main/java/io/hyscale/generator/services/constants/ManifestGenConstants.java
- manifest-generator/generator-services/src/main/java/io/hyscale/generator/services/model/ManifestResource.java
- manifest-generator/generator-services/src/main/java/io/hyscale/generator/services/model/PodChecksum.java
- manifest-generator/generator-services/src/main/java/io/hyscale/generator/services/plugins/ConfigMapDataHandler.java
- manifest-generator/generator-services/src/main/java/io/hyscale/generator/services/plugins/HealthChecksHandler.java
- manifest-generator/generator-services/src/main/java/io/hyscale/generator/services/plugins/ImagePullSecretHandler.java
- manifest-generator/generator-services/src/main/java/io/hyscale/generator/services/plugins/LabelsAddonHandler.java
- manifest-generator/generator-services/src/main/java/io/hyscale/generator/services/plugins/PodAnnotationHandler.java
- manifest-generator/generator-services/src/main/java/io/hyscale/generator/services/plugins/SecretsDataHandler.java
- manifest-generator/generator-services/src/main/java/io/hyscale/generator/services/utils/AgentConfigMapBuilder.java
- manifest-generator/generator-services/src/main/java/io/hyscale/generator/services/utils/AgentSecretBuilder.java
- manifest-generator/generator-services/src/main/java/io/hyscale/generator/services/utils/AgentVolumeMountBuilder.java
- manifest-generator/generator-services/src/main/java/io/hyscale/generator/services/utils/ChecksumProvider.java
- manifest-generator/generator-services/src/main/java/io/hyscale/generator/services/utils/ConfigMapDataUtil.java
- manifest-generator/generator-services/src/main/java/io/hyscale/generator/services/utils/SecretsDataUtil.java
- manifest-generator/generator-services/src/main/resources/config/plugins.txt
- workflow-controller/controller-service/src/main/java/io/hyscale/controller/commands/deploy/HyscaleDeployServiceCommand.java
Fixes: https://github.com/hyscale/hyscale/issues/210
> Reflect config map and secret changes in pod

- commons/src/main/java/io/hyscale/commons/constants/ToolConstants.java
- commons/src/main/java/io/hyscale/commons/framework/patch/StrategicPatch.java
- commons/src/main/java/io/hyscale/commons/io/HyscaleFilesUtil.java
- commons/src/main/java/io/hyscale/commons/io/TailLogFile.java
- commons/src/main/java/io/hyscale/commons/utils/HyscaleContextUtil.java
- commons/src/main/java/io/hyscale/commons/utils/MustacheTemplateResolver.java
- commons/src/main/java/io/hyscale/commons/utils/ResourceSelectorUtil.java
- commons/src/test/java/io/hyscale/commons/utils/ResourceLabelBuilderTests.java
Fixed blocker issues in static code analysis related to commons module.
> Fixing blockers of sonar code analysis in commons module.

- deployer/deployer-services/src/main/java/io/hyscale/deployer/services/constants/DeployerConstants.java
- deployer/deployer-services/src/main/java/io/hyscale/deployer/services/handler/PodParentHandler.java
- deployer/deployer-services/src/main/java/io/hyscale/deployer/services/handler/ResourceHandlers.java
- deployer/deployer-services/src/main/java/io/hyscale/deployer/services/handler/ResourceLifeCycleHandler.java
- deployer/deployer-services/src/main/java/io/hyscale/deployer/services/handler/impl/K8sAuthenticationHandler.java
- deployer/deployer-services/src/main/java/io/hyscale/deployer/services/handler/impl/NamespaceHandler.java
- deployer/deployer-services/src/main/java/io/hyscale/deployer/services/handler/impl/V1ConfigMapHandler.java
- deployer/deployer-services/src/main/java/io/hyscale/deployer/services/handler/impl/V1DeploymentHandler.java
- deployer/deployer-services/src/main/java/io/hyscale/deployer/services/handler/impl/V1EventHandler.java
- deployer/deployer-services/src/main/java/io/hyscale/deployer/services/handler/impl/V1HorizontalPodAutoScalerHandler.java
- deployer/deployer-services/src/main/java/io/hyscale/deployer/services/handler/impl/V1PersistentVolumeClaimHandler.java
- deployer/deployer-services/src/main/java/io/hyscale/deployer/services/handler/impl/V1PodHandler.java
- deployer/deployer-services/src/main/java/io/hyscale/deployer/services/handler/impl/V1ReplicaSetHandler.java
- deployer/deployer-services/src/main/java/io/hyscale/deployer/services/handler/impl/V1SecretHandler.java
- deployer/deployer-services/src/main/java/io/hyscale/deployer/services/handler/impl/V1ServiceHandler.java
- deployer/deployer-services/src/main/java/io/hyscale/deployer/services/handler/impl/V1StatefulSetHandler.java
- deployer/deployer-services/src/main/java/io/hyscale/deployer/services/handler/impl/V1StorageClassHandler.java
- deployer/deployer-services/src/main/java/io/hyscale/deployer/services/handler/impl/V1beta2DeploymentHandler.java
- deployer/deployer-services/src/main/java/io/hyscale/deployer/services/handler/impl/V1beta2StatefulSetHandler.java
> Fixing blocker for static code analysis deployer module

- dockerfile-generator/dockerfile-gen-services/src/main/java/io/hyscale/dockerfile/gen/services/predicates/DockerfileGenPredicates.java
- service-spec/service-spec-commons/src/main/java/io/hyscale/servicespec/commons/model/service/ReplicasDeserializer.java
- workflow-controller/controller-service/src/main/java/io/hyscale/controller/invoker/DeployComponentInvoker.java
- workflow-controller/controller-service/src/main/java/io/hyscale/controller/invoker/StatusComponentInvoker.java
- workflow-controller/controller-service/src/main/java/io/hyscale/controller/validator/impl/VolumeValidator.java
Blockers from modules :
1. Workflow Controller
2.Service Spec
3. Docker File Generator
> Fixing blockers of static code analysis

- commons/src/main/java/io/hyscale/commons/models/Auth.java
- manifest-generator/generator-services/src/main/java/io/hyscale/generator/services/plugins/ImagePullSecretHandler.java
- workflow-controller/controller-service/src/main/java/io/hyscale/controller/builder/ImageRegistryBuilder.java
Reverting the code due to build failure.
> Fixing major code smells reported in sonar code analysis in commons module

- .github/workflows/release.yaml
> Release to upload multiple binaries to github release pages

- examples/README.md
- examples/quickstart/go-lang/README.md
1. Added Readme for golang quickstart sample example
2. Updated examples Readme to point golang quickstart for getting started
> [docs] updated examples Readme 

- README.md
1. Added TOC
2. "docker login" prerequisite clarification
> [docs] updated Readme

- commons/src/test/java/io/hyscale/commons/utils/HyscaleFilesUtilTests.java
- commons/src/test/java/io/hyscale/commons/utils/LogProcessorTests.java
Observed test failures on Windows machine.
> Fix for junits compilation failure on windows

- scripts/hacks/create-admin-token.sh
1. creates a cluster admin service account and updates the kubeconfig file with the admin token
> Added a utility script to create cluster admin token and update kubeconfig (issue 318)

- docs/hyscale-commands-reference.md
- invoker/container/container.go
- workflow-controller/controller-service/src/main/resources/logback.xml
1. changed logback.xml to take log level from env (default is info)
2. updated invoker go script to pass Env variable to hyscale jar
> taking loglevel from Env variable HYS_LOG_LEVEL

- deployer/deployer-core/src/main/java/io/hyscale/deployer/core/model/DeploymentStatus.java
- deployer/deployer-services/src/main/java/io/hyscale/deployer/services/handler/impl/V1DeploymentHandler.java
- deployer/deployer-services/src/main/java/io/hyscale/deployer/services/handler/impl/V1StatefulSetHandler.java
- deployer/deployer-services/src/main/java/io/hyscale/deployer/services/model/PodStatus.java
- deployer/deployer-services/src/main/java/io/hyscale/deployer/services/model/PodStatusUtil.java
- deployer/deployer-services/src/main/java/io/hyscale/deployer/services/util/K8sPodUtil.java
- deployer/troubleshooting-integration/src/main/java/io/hyscale/troubleshooting/integration/builder/TroubleshootingContextCollector.java
- deployer/troubleshooting-integration/src/main/java/io/hyscale/troubleshooting/integration/conditions/PodStatusCondition.java
- deployer/troubleshooting-integration/src/main/java/io/hyscale/troubleshooting/integration/models/AbstractedErrorMessage.java
- workflow-controller/controller-service/src/main/java/io/hyscale/controller/invoker/StatusComponentInvoker.java
-- Added pod status as terminating.
-- Added scaling down service status.
-- Fixed wait for scaling down replicas.
-- Fixed running to not-running status of services with zero replicas.
> Changes to handle scaling of replicas with patch.

- deployer/deployer-services/src/main/java/io/hyscale/deployer/services/client/GenericK8sClient.java
- deployer/deployer-services/src/main/java/module-info.java
Removed plugins that are not required. Also did respective code changes.
> Fix: Java-doc plugin errors.

- .github/containerscan/allowedlist.yaml
- deployer/deployer-services/src/test/java/io/hyscale/deployer/services/util/ServiceUtilTest.java
- image-builder/pom.xml
- manifest-generator/generator-services/src/test/java/io/hyscale/generator/services/plugins/ImageHandlerTest.java
- manifest-generator/generator-services/src/test/java/io/hyscale/generator/services/plugins/ImagePullSecretHandlerTest.java
- manifest-generator/generator-services/src/test/java/io/hyscale/generator/services/plugins/PortsHandlerTest.java
- manifest-generator/generator-services/src/test/java/io/hyscale/generator/services/plugins/ReplicasHandlerTest.java
- manifest-generator/generator-services/src/test/java/io/hyscale/generator/services/plugins/ResourceLimitHandlerTest.java
- manifest-generator/generator-services/src/test/java/io/hyscale/generator/services/plugins/ServiceTypeTest.java
- manifest-generator/generator-services/src/test/java/io/hyscale/generator/services/plugins/StartCommandHandlerTest.java
- manifest-generator/generator-services/src/test/java/io/hyscale/generator/services/plugins/VolumeMountsHandlerTest.java
- manifest-generator/generator-services/src/test/java/io/hyscale/generator/services/plugins/VolumeTemplatesHandlerTest.java
- manifest-generator/generator-services/src/test/java/io/hyscale/generator/services/plugins/VolumesHandlerTest.java
- manifest-generator/generator-services/src/test/java/io/hyscale/generator/services/processor/PluginProcessorTest.java
- pom.xml
- service-spec/pom.xml
TODO: Few of the vulnerabilities will be resolved after updating docker-java-client and kubernetes-java-client to the latest revision. That would require few other changes(due to changes in source models), Will be taking them in separate PRs
> Dependency changes for resolving vulnerabilities

- pom.xml
- service-spec/schema-validator/pom.xml
- service-spec/schema-validator/src/main/resources/script/fetch.sh
- service-spec/schema-validator/src/main/resources/script/verify.sh
> Fetching hspec & hprof from master branch instead of release branch
